name: Package & Publish
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: OpenJDK download
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate .m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "<settings><servers><server><id>github</id><username>Delfimarime</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
      - name: API installation
        run: mvn -B clean deploy --file api/pom.xml
      - name: TESSERACT package
        run: mvn -B clean deploy --file impl/pom.xml
